import uuid
from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy.orm import Session

from app.models.transaction import Transaction
from app.models.dispute import Dispute, DisputeStatus
from app.models.evidence import Evidence, UploaderRole, EvidenceType, CredibilityLabel
from app.models.timeline_event import TimelineEvent
from app.decision_engine.reason_codes import infer_reason_code
from app.services.recommendation_service import compute_recommendation

# Fixed id — the frontend's Landing page links directly to
# /disputes/dsp_8841 ("View a live workspace"), so this id must stay
# stable across restarts for that link to keep working.
SEED_DISPUTE_ID = "dsp_8841"


def _uid(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:10]}"


def _evidence(dispute_id, uploader, etype, credibility, summary, ts):
    return Evidence(
        id=_uid("ev"),
        dispute_id=dispute_id,
        uploader=uploader,
        type=etype,
        credibility=credibility,
        summary=summary,
        created_at=ts,
    )


def _snapshot_recommendation(db, dispute, evidence_so_far, previous, updated_at):
    """
    Sprint 6: seed data is generated by calling the SAME
    compute_recommendation() the live app uses at evidence-submission
    time, rather than hand-written recommendation text. This was a real
    inconsistency worth fixing — the original dsp_8841 seed copy
    (written in Sprint 1, before the Decision Engine existed) had never
    been regenerated and no longer matched what the real engine would
    actually produce for that evidence once Sprint 5 landed.
    """
    rec = compute_recommendation(dispute, evidence_so_far, previous)
    rec.updated_at = updated_at  # override server_default for narrative pacing
    db.add(rec)
    return rec


def seed_if_empty(db: Session) -> None:
    if db.query(Dispute).first() is not None:
        return  # already seeded — nothing to do

    # -----------------------------------------------------------------
    # Flagship demo dispute — linked directly from Landing.
    # -----------------------------------------------------------------
    txn = Transaction(
        id="txn_55291",
        merchant_name="Harborline Stays",
        amount=Decimal("340.00"),
        currency="USD",
        occurred_at=datetime(2026, 7, 12, 10, 3, tzinfo=timezone.utc),
    )
    db.add(txn)

    dispute = Dispute(
        id=SEED_DISPUTE_ID,
        transaction_id=txn.id,
        customer_name="Priya Nair",
        merchant_name="Harborline Stays",
        reason="Item not as described",
        reason_code=infer_reason_code("Item not as described"),
        amount=Decimal("340.00"),
        currency="USD",
        status=DisputeStatus.IN_NEGOTIATION,
        created_at=datetime(2026, 7, 18, 14, 12, tzinfo=timezone.utc),
    )
    db.add(dispute)

    for title, description, ts in [
        ("Booking confirmed", "Reservation made for a 2-night stay, Deluxe Harbor View room.",
         datetime(2026, 7, 12, 10, 2, tzinfo=timezone.utc)),
        ("Payment captured", "$340.00 charged to card ending 4471.",
         datetime(2026, 7, 12, 10, 3, tzinfo=timezone.utc)),
        ("Check-in recorded", "Guest checked in at property front desk.",
         datetime(2026, 7, 16, 15, 41, tzinfo=timezone.utc)),
        ("Guest message sent", "Guest messaged front desk: room did not match listing photos.",
         datetime(2026, 7, 16, 16, 20, tzinfo=timezone.utc)),
        ("Review posted", "Guest left a 2-star review citing room discrepancy.",
         datetime(2026, 7, 18, 9, 15, tzinfo=timezone.utc)),
        ("Dispute filed", "Cardholder opened a dispute: item not as described.",
         datetime(2026, 7, 18, 14, 12, tzinfo=timezone.utc)),
    ]:
        db.add(TimelineEvent(id=_uid("evt"), dispute_id=dispute.id, timestamp=ts, title=title, description=description))

    early_evidence = [
        _evidence(dispute.id, UploaderRole.system, EvidenceType.SYSTEM_RECORD, CredibilityLabel.VERIFIED_TRANSACTION,
                  "Transaction record — $340.00 to Harborline Stays on Jul 12.",
                  datetime(2026, 7, 18, 14, 12, 5, tzinfo=timezone.utc)),
        _evidence(dispute.id, UploaderRole.system, EvidenceType.SYSTEM_RECORD, CredibilityLabel.TIMESTAMPED_RECEIPT,
                  "Booking confirmation — Deluxe Harbor View, 2 nights.",
                  datetime(2026, 7, 18, 14, 12, 6, tzinfo=timezone.utc)),
        _evidence(dispute.id, UploaderRole.cardholder, EvidenceType.IMAGE, CredibilityLabel.CUSTOMER_STATEMENT,
                  "Photo of the room actually provided at check-in.",
                  datetime(2026, 7, 18, 14, 20, tzinfo=timezone.utc)),
    ]
    for e in early_evidence:
        db.add(e)

    later_evidence = early_evidence + [
        _evidence(dispute.id, UploaderRole.merchant, EvidenceType.SYSTEM_RECORD, CredibilityLabel.GPS_CONFIRMED,
                  "Front-desk check-in log with device GPS confirmation.",
                  datetime(2026, 7, 18, 15, 2, tzinfo=timezone.utc)),
        _evidence(dispute.id, UploaderRole.merchant, EvidenceType.TEXT, CredibilityLabel.MERCHANT_STATEMENT,
                  "Merchant statement: guest was offered a room change, declined.",
                  datetime(2026, 7, 18, 15, 5, tzinfo=timezone.utc)),
    ]
    for e in later_evidence[len(early_evidence):]:
        db.add(e)

    first_rec = _snapshot_recommendation(
        db, dispute, early_evidence, None, datetime(2026, 7, 18, 14, 21, tzinfo=timezone.utc)
    )
    _snapshot_recommendation(
        db, dispute, later_evidence, first_rec, datetime(2026, 7, 18, 15, 6, tzinfo=timezone.utc)
    )

    # -----------------------------------------------------------------
    # Original filler disputes (kept for backward compatibility with
    # Analyst View / earlier sprints) — unchanged from prior sprints.
    # -----------------------------------------------------------------
    for d_id, txn_id, merchant, reason, amount, status, created in [
        ("dsp_8790", "txn_55110", "Harborline Stays", "Duplicate charge",
         Decimal("89.50"), DisputeStatus.RESOLVED, datetime(2026, 7, 10, 9, 3, tzinfo=timezone.utc)),
        ("dsp_8705", "txn_54932", "Northgate Electronics", "Item not received",
         Decimal("212.75"), DisputeStatus.OPEN, datetime(2026, 7, 21, 18, 47, tzinfo=timezone.utc)),
        ("dsp_8622", "txn_54810", "Harborline Stays", "Service not rendered",
         Decimal("150.00"), DisputeStatus.CLOSED, datetime(2026, 6, 30, 11, 22, tzinfo=timezone.utc)),
    ]:
        db.add(Transaction(id=txn_id, merchant_name=merchant, amount=amount, currency="USD", occurred_at=created))
        db.add(Dispute(id=d_id, transaction_id=txn_id, customer_name="Priya Nair", merchant_name=merchant,
                        reason=reason, reason_code=infer_reason_code(reason), amount=amount, currency="USD",
                        status=status, created_at=created))

    # -----------------------------------------------------------------
    # Sprint 6: demo scenarios covering each of the five possible
    # Decision Engine outcomes — for judges/demoers to browse via
    # Analyst View without needing to construct a scenario live.
    # -----------------------------------------------------------------
    _seed_demo_scenario(
        db,
        dispute_id="dsp_demo_approve",
        txn_id="txn_demo_approve",
        merchant_name="TechGear Direct",
        reason="Item not received",
        amount=Decimal("129.00"),
        created=datetime(2026, 7, 22, 10, 0, tzinfo=timezone.utc),
        evidence=[
            (UploaderRole.cardholder, EvidenceType.TEXT, CredibilityLabel.CUSTOMER_STATEMENT,
             "Ordered a laptop stand; tracking shows no movement in 9 days and it never arrived."),
        ],
    )

    _seed_demo_scenario(
        db,
        dispute_id="dsp_demo_reject",
        txn_id="txn_demo_reject",
        merchant_name="Riverside Bistro",
        reason="Item not received",
        amount=Decimal("64.20"),
        created=datetime(2026, 7, 22, 11, 0, tzinfo=timezone.utc),
        evidence=[
            (UploaderRole.merchant, EvidenceType.SYSTEM_RECORD, CredibilityLabel.TIMESTAMPED_RECEIPT,
             "Delivery confirmation — order picked up in person at 7:42 PM, signed for by the cardholder."),
        ],
    )

    _seed_demo_scenario(
        db,
        dispute_id="dsp_demo_request_evidence",
        txn_id="txn_demo_request_evidence",
        merchant_name="Northgate Electronics",
        reason="Item not as described",
        amount=Decimal("340.00"),
        created=datetime(2026, 7, 22, 12, 0, tzinfo=timezone.utc),
        evidence=[],
    )

    _seed_demo_scenario(
        db,
        dispute_id="dsp_demo_escalate",
        txn_id="txn_demo_escalate",
        merchant_name="Downtown Parking Co",
        reason="Other",
        amount=Decimal("18.50"),
        created=datetime(2026, 7, 22, 13, 0, tzinfo=timezone.utc),
        evidence=[
            (UploaderRole.cardholder, EvidenceType.TEXT, CredibilityLabel.CUSTOMER_STATEMENT,
             "Charged twice for the same parking session, but the reason doesn't fit any standard category."),
        ],
    )

    db.commit()


def _seed_demo_scenario(db, *, dispute_id, txn_id, merchant_name, reason, amount, created, evidence):
    """Creates one demo dispute with the given evidence already submitted,
    and computes its recommendation via the real engine — used for the
    four Sprint 6 demo scenarios (Approve / Reject / Request Additional
    Evidence / Escalate)."""
    db.add(Transaction(id=txn_id, merchant_name=merchant_name, amount=amount, currency="USD", occurred_at=created))
    dispute = Dispute(
        id=dispute_id,
        transaction_id=txn_id,
        customer_name="Priya Nair",
        merchant_name=merchant_name,
        reason=reason,
        reason_code=infer_reason_code(reason),
        amount=amount,
        currency="USD",
        status=DisputeStatus.OPEN if not evidence else DisputeStatus.IN_NEGOTIATION,
        created_at=created,
    )
    db.add(dispute)
    db.add(
        TimelineEvent(
            id=_uid("evt"), dispute_id=dispute_id, timestamp=created,
            title="Dispute Created", description=f"Cardholder opened a dispute: {reason}.",
        )
    )

    evidence_items = []
    for uploader, etype, credibility, summary in evidence:
        item = _evidence(dispute_id, uploader, etype, credibility, summary, created)
        db.add(item)
        evidence_items.append(item)
        db.add(
            TimelineEvent(
                id=_uid("evt"), dispute_id=dispute_id, timestamp=created,
                title="Merchant Response Added" if uploader == UploaderRole.merchant else "Evidence Uploaded",
                description=summary,
            )
        )

    _snapshot_recommendation(db, dispute, evidence_items, None, created)
